eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/    # 注册服务地址
  instance:
    prefer-ip-address: true   #访问的路径变为IP地址
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5
    appname: web服务 #如果现在超过了5秒的间隔（默认90秒）

server:
  port: 9040
spring:
  profiles:
    active: dev
  application:
    name: service-web    # 服务名称
  datasource:
    url: jdbc:mysql://120.79.238.208:3306/spring_cloud?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: Glory!1998
    driver-class: com.mysql.jdbc.Driver

#  redis:
#    host: 127.0.0.1
#    port: root
#    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
