spring:
  application:
    name: friend-user-service
  #热部署
#  devtools: 
#    restart: 
#      enabled: true  #热部署生效
#      additional-paths: src/main/java #设置需要重启的目录
#      exclude: com.rong.friend.*,WEB-INF/**  #排除不需要重启的目录