server:
  port: 9060

spring:
  application:
    name: auth-server
  zipkin:
      base-url: http://localhost:9411
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://120.79.238.208:3306/friend_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Glory!1998
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 120.79.238.208
    port: 6379
    password: glory1998
eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1