eureka:
  client:
    service-url:
      defauleZone: http://peer1:8761/eureka/ #http://friendeureka:gloryfriend@peer1:8761/eureka/,http://friendeureka:gloryfriend@peer2:8762/eureka/
server:
  port: 8781
spring:
  application:
    name: friend-service-zuul
  #redis缓存配置
  redis:
    database: 0
    host: 120.79.238.208
    port: 6379
    password: glory1998
    timeout: 10000
    lettuce:
      pool:
        max-wait: -1
        max-active: 10000
        max-idle: 100
        min-idle: 10
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /api-user/**
      serviceId: friend-user-service
    api-b:
      path: /api-chat/**
      serviceId: friend-chat-service
#feign
#  hystrix
#    enabled: true