eureka:
  client:
    service-url:
      defauleZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
server:
  port: 8781
spring:
  application:
    name: friend-gateway-service
  #动态刷新配置文件
  rabbitmq:
    host: 120.79.238.208
    password: guest
    port: 5672
    username: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-api
        uri: lb://friend-user-service
        predicates:
        - Path=/user-api/**
        filters:
        - SwaggerHeaderFilter
        - StripPrefix=1
      - id: chat-api
        uri: lb://friend-chat-service
        predicates:
        - Path=/chat-api/**
        filters:
        - StripPrefix=1
      - id: oauth-api
        uri: lb://friend-oauth-server
        predicates:
        - Path=/oauth-api/**
        filters:
        - SwaggerHeaderFilter
        - StripPrefix=1