server:
  port: 9060

spring:
  application:
    name: friend-oauth-server
  zipkin:
      base-url: http://localhost:9411
  redis:
    host: 120.79.238.208
    port: 6379
    password: glory1998
  #动态刷新配置文件
  rabbitmq:
    host: 120.79.238.208
    password: guest
    port: 5672
    username: guest
eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://peer1:8761/eureka/,http://peer2:9762/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# ribbon:
#   ReadTimeout: 30000
#   ConnectTimeout: 60000
#   MaxAutoRetries: 0
#   MaxAutoRetriesNextServer: 1