eureka:
  client:
    service-url:
      defauleZone: http://friendeureka:gloryfriend@peer1:8761/eureka/,http://friendeureka:gloryfriend@peer2:8762/eureka/
server:
  port: 8781
spring:
  application:
    name: friend-service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: friend-user-service