eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ #,http://peer2:8762/eureka/
server:
  port: 8771
spring:
  application:
    name: friend-user-service
  zipkin:
    base-url: http://localhost:9411
  #redis缓存配置
  redis:
    database: 0
    host: 120.79.238.208
    port: 6379
    password: glory1998
    timeout: 5000
    lettuce:
      pool:
        max-wait: -1
        max-active: 10000
        max-idle: 100
        min-idle: 10
  datasource:
    name: friend
    type: com.alibaba.druid.pool.DruidDataSource
    #使用druid数据源
    druid:
      url: jdbc:mysql://120.79.238.208:3306/friend_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: Glory!1998
      #监控统计拦击filters
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      #配置初始化大小，最大/最小
      initial-size: 1
      min-idle: 1
      max-active: 20
      #配置连接超时等待时间
      max-wait: 60000
      #间隔多久进行一次检验，检验需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #动态刷新配置文件
  rabbitmq:
    host: 120.79.238.208
    password: guest
    port: 5672
    username: guest
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rong.friend.model