eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
server:
  port: 8771
spring:
  application:
    name: friend-user-service
  zipkin:
    base-url: http://localhost:9411