eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
server:
  port: 8771
spring:
  application:
    name: friend-user-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    name: friend
    type: com.alibaba.druid.pool.DruidDataSource
    #使用druid数据源
    druid:
      url: jdbc:mysql://116.85.23.71:3306/friend_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: Root!2018
      #监控统计拦击filters
      driver-class-name: com.mysql.jdbc.Deiver
      filters: stat
      #配置初始化大小，最大/最小
      initial-size: 1
      min-idle: 1
      max-active: 20
      #配置连接超时等待时间
      max-wait: 60000
      #间隔多久进行一次检验，检验需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rong.friend.entity