server:
  port: 9010
  context-path: /
spring:
  application:
    name: service-gateway
  cloud:
    config:
      name: service-gateway
      profile: dev
      uri: http://127.0.0.1:8888
management:
  security:
    enabled: false
endpoints:
  refresh:
    enabled: true



